### PR TITLE
Fix MaliProfiler::init() exception: "Failed settings flags ioctl." on Mali-G710

### PR DESCRIPTION
**Pull request by ming4883**
Reference https://github.com/ARM-software/HWCPipe/issues/57

### CODE REVIEW

**Comment by ming4883** [comment]
@solidpixel Would you please help reviewing this PR? If the purposed changes are correct, I can help integrating the latest version of HWCPipe into renderdoc for wider range of Mali devices support.

**Comment by solidpixel** [comment]
Yes, I can help review. 

How does the integration with RenderDoc work? Given how tile-based renders work, it is likely to have serious limitations (e.g. you can profile render passes, if careful with fences, but not draw calls).

**Comment by ming4883** [comment]
Yes, I have confirmed this is working in RenderDoc on both Dimensity 1200 and Dimensity 9000 SoC.
And the author require HWCPipe to confirm this PR before the fix can be merged into the next RenderDoc release.



<a href='https://imgur.com/a/hc2ZPOO'>image link</a>

**Review by solidpixel — APPROVED** [review]

**Comment by solidpixel** [comment]
Merged.

BUT if RenderDoc is using this to present per-draw performance data, the data is highly likely to be wrong. The way counters work in Mali cannot be used for per-draw timing.

**Pull request merged**
